spring.application.name=barber-booking-api
spring.datasource.url=jdbc:postgresql://localhost:5432/barber_booking
spring.datasource.username=postgres
spring.datasource.password=astrapi100asasas

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true